# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["nodejs-18_x", "postgresql"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "node src/index.js"

[variables]
NODE_ENV = "production"
